namespace: grafana

images:
- name: grafana/grafana
  newTag: 6.6.2

resources:
- manifest.yaml

generators:
- secrets.yaml

configMapGenerator:
- name: dashboards
  files:
  - dashboards/prometheus.json
  - dashboards/traefik.json
- name: grafana
  files:
  - configs/dashboardproviders.yaml
  - configs/datasources.yaml
  - configs/plugins
