namespace: grafana

images:
- name: grafana/grafana
  newTag: 6.6.2

resources:
- manifest.yaml

generators:
- secrets/grafana/secrets.yaml

configMapGenerator:
- name: dashboards
  files:
  - configs/dashboards/prometheus.json
  - configs/dashboards/traefik.json
- name: grafana
  files:
  - configs/grafana/dashboardproviders.yaml
  - configs/grafana/datasources.yaml
  - configs/grafana/plugins
