apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana
              key: admin-password
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gafana
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana 
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`grafana.bender.sway.org`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: gafana
      port: 3000
    middlewares:
    - name: redirect

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: securegrafana
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`grafana.bender.sway.org`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: gafana
      port: 3000
  tls:
    certResolver: myresolver
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "ZVZWYndsbE84NTdxRzhmcEJ4RnBNTDZZWTUyUXc2YlNLS2l1N2huQQ=="
